version: '3'
services:
  node01:
    image: 'python:3.7-alpine'
    volumes:
      - './:/app'
    ports:
      - '8081:8081'
    command: 'python /app/run-raft.py 0.0.0.0:8081 node02:8082 node03:8083'
  node02:
    image: 'python:3.7-alpine'
    volumes:
      - './:/app'
    ports:
      - '8082:8082'
    command: 'python /app/run-raft.py 0.0.0.0:8082 node01:8081 node03:8083'
  node03:
    image: 'python:3.7-alpine'
    volumes:
      - './:/app'
    ports:
      - '8083:8083'
    command: 'python /app/run-raft.py 0.0.0.0:8083 node01:8081 node02:8082'
